### ISSUE TITLE
Transactional e-mails screen does not load templates of specific store view

### ISSUE THREAD

**Issue by dverkade** [yireo/Yireo_EmailOverride#23] opened 2016-09-26 14:31 UTC
Hi,

In the transactional e-mail screen you can only change or load the standard e-mail templates per store. Once you have created templates with the Override module it's not possiblo to load them in de transactionel e-mail screen and change them. See screenshot: 

![image](https://cloud.githubusercontent.com/assets/1058480/18837993/178f83f4-8406-11e6-84fb-a31244374147.png)

Exepcted behavior is the this screen should add a "store view" dropdown in the transactionel e-mail screen so it will load the e-mail from the specified store or design folder.

**Comment by jissereitsma** [comment] 2016-10-03 12:33
I think this is a duplicate of https://github.com/yireo/Yireo_EmailOverride/issues/22 and indeed a shortcoming of the extension. I hope to work sooner or later on this (or see an incoming PR for this).

**Comment by jissereitsma** [comment] 2017-02-26 06:21
Because it is a duplicate issue, I'm closing this for now.

**Closed by jissereitsma** 2017-02-26 06:21 UTC
